name: hive_mobile
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.7.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  google_sign_in: ^6.1.3
  provider: ^6.0.5
  percent_indicator: ^4.2.3
  flutter_polls: ^0.1.2
  go_router: ^8.0.1
  badges: 3.1.1
  intl: ^0.17.0
#  scrollable_clean_calendar: ^1.4.1
  scrollable_positioned_list: ^0.3.8
  http: ^0.13.6
  get_it: ^7.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600