name: hive_mobile
description: A new Flutter project.


version: 1.0.1+5

environment:
  sdk: '>=2.19.6 <3.7.12'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  google_sign_in: ^6.1.5
  provider: ^6.0.5
  go_router: ^8.0.1
  badges: 3.1.1
  intl: ^0.17.0
  scrollable_positioned_list: ^0.3.8
  http: ^0.13.6
  get_it: ^7.6.0
  flutter_animate: ^4.2.0
  timeago: ^3.3.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  cached_network_image: ^3.2.3
  path_provider: ^2.0.15
  image_pickers: ^2.0.4+5
  fluttertoast: ^8.2.2
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.1
  uuid: ^4.1.0
  sliver_tools: ^0.2.12
  email_validator: ^2.1.17
  form_validator: ^2.1.1
  url_launcher: ^6.1.11
  flutter_inappwebview: ^5.8.0
  permission_handler: ^11.0.1
  flutter_downloader: ^1.10.5
  encrypt: ^5.0.1
  web_socket_client: ^0.1.0
  flutter_dotenv: ^5.1.0
  animated_flip_counter: ^0.2.6
  sentry_flutter: ^7.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: any
  build_runner: any
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.3.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/launcher_icon.png"
  adaptive_icon_foreground: "assets/icons/ic_launcher_foreground.png"
  adaptive_icon_background: "assets/icons/ic_launcher_foreground.png"


flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
