class FileUploadPurpose {
  static String PROFILE_PICTURE = "PROFILE_PICTURE";

  static String ANNOUNCEMENT_POST_ATTACHMENT = "ANNOUNCEMENT_POST_ATTACHMENT";

  static String ACTIVITY_BANNER = "ACTIVITY_BANNER";

  static String MESSAGE_ATTACHMENT = "MESSAGE_ATTACHMENT";

  static String NOTIFICATION_ATTACHMENT = "NOTIFICATION_ATTACHMENT";

  static String SERVICE_REQUEST_ATTACHMENT = "SERVICE_REQUEST_ATTACHMENT";

  static String EXTERNAL_GRADE_RESULT_FILE = "EXTERNAL_GRADE_RESULT_FILE";

  static String AWARD_ATTACHMENT = "AWARD_ATTACHMENT";

  static String UNIVERSITY_APPLICATION_DOCUMENT =
      "UNIVERSITY_APPLICATION_DOCUMENT";

  static String ACHIEVEMENT_ATTACHMENT = "ACHIEVEMENT_ATTACHMENT";
}
